### ISSUE TITLE
IOError: cannot write mode RGBA as JPEG

### ISSUE THREAD

**Issue by akkshita** [allexpy/image-converter#2]
python converter.py 
Traceback (most recent call last):
  File "converter.py", line 75, in <module>
    processImage()
  File "converter.py", line 57, in processImage
    compress_image(image, infile)
  File "converter.py", line 36, in compress_image
    image.save(first_name, quality=85)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1969, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python2.7/dist-packages/PIL/JpegImagePlugin.py", line 622, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
IOError: cannot write mode RGBA as JPEG

**Comment by Dreyk007** [comment]
try to use Python 3

**Comment by rdtandel** [comment]
> 
> 
> try to use Python 3

im on python 3.7, and got same error
